### ISSUE TITLE
State value delayed in content.ts

### ISSUE THREAD

**Issue by mo-vic** [vantezzen/plasmo-state#1]
I try update state in popup.tsx, and retrieve the value in contents.ts in the "load" event listener, however, the value is the default value.

I also setup a timer to see if the state value was loaded after the load event:
```js
setInterval(() => {
  console.log(state.current.counter)
}, 1000)
```

and the state value is the stored value in each time triggered log info, so I am guessing If the state value is delayed?

**Comment by vantezzen** [comment]
Are you using "load" or "ready" as the event you are listening for?

**Comment by mo-vic** [comment]
I'm using the load event.

**Comment by vantezzen** [comment]
Thanks for the info - didn't even know a "load" event is fired. Can you try using the "ready" event as described at https://github.com/vantezzen/plasmo-state/tree/main#listen-for-ready-event - this should only fire once a status sync with other contexts has completed

**Comment by mo-vic** [comment]
I want to change some ui components once the web was loaded. However, due to the network condition, sometimes the web might take a long time to load, and if I add my logic in the above ready event, it is possible to miss some changes.

**Comment by mo-vic** [comment]
I found that the official plasmo-storage implementation syncs the state before the `load` event, so I'm currently using it.
