### ISSUE TITLE
Feature: Add StateEnvironment.Offscreen

### ISSUE THREAD

**Issue by dimadolgopolovn** [vantezzen/plasmo-state#2]
Now that offscreen is in released, you might want to use plasmo-state there.
https://developer.chrome.com/docs/extensions/reference/offscreen/

**Comment by vantezzen** [comment]
Looks like the offscreen page should be able to use `StateEnvironment.Background` - I'll look into this and add `StateEnvironment.Offscreen` to use the same logic if it works. Until then, using `StateEnvironment.Background` in offscreen pages should work directly, too.

**Comment by vantezzen** [comment]
Added with 2.1.0
